[project]
name = "smart-contract-bug-bounty-platform"
description = "Blockchain project: smart-contract-bug-bounty-platform"
authors = ["Arinzeroxy289 <>"]
telemetry = false
cache_dir = ".clarinet"

[contracts.main-contract]
path = "contracts/main-contract.clar"
clarinet_version = "1.0.0"

[requirements]
