[project]
name = "smart-contract-bug-bounty-platform"
description = "Blockchain project: smart-contract-bug-bounty-platform"
authors = ["Automated Builder <automation@blockchain.dev>"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.vulnerability-bounty-manager]
path = "contracts/vulnerability-bounty-manager.clar"
depends_on = []

[contracts.security-reputation-tracker]
path = "contracts/security-reputation-tracker.clar"
depends_on = []

